# Plugins
plugins:
  - jekyll-paginate
  - bourbon
  - jekyll-gist
  - jekyll-sitemap

# SEO settings
title: "Script"
title2: "Ops"
description: "Dev+Sec+Ops Tools and Primers"
keywords: "security, powershell, admin, devops, automation, GRC"
url: "https://scriptops.com"

# Analytics and comments
google_analytics: "UA-79423450-2"
repo: "https://github.com/scriptops.com"
# disqus_shortname: "scriptops"
comments: true

# Filtering Content
show_drafts: null
limit_posts: 0
future: false
unpublished: false

# Directories
source: ./
destination: ./_site

# Collections
collections:
  posts:
    output: true

# Author settings
author:
  name: "Jan Bilinski"
  job: "IT Systems Engineer<img style='display:none;position:absolute;' src='https://readme-typing-svg.herokuapp.com?font=Noto+Sans+Mono&size=24&duration=3000&pause=1000&color=0086B3&vCenter=true&width=350&height=24&lines=IT+Systems+Administrator;Infrastructure+Engineer;Build+Platform+Engineer;Cyber+Security+Engineer' alt='Systems Engineer' />"
  content: "Novel <b>tools</b> and primers for my community."
  quote: "DevOps isn't about automation, just as astronomy isn't about telescopes. ― Gene Kim, The DevOps Handbook"
  url: https://jamie.bilinski.org
  github: https://nli.me/gh-profile
  twitter: https://twitter.com/ScriptOps
  linkedin: https://nli.me/in-profile
  posts: https://mugtrap.com
  thumb: https://gravatar.com/avatar/7ef7f59e6bfa3188f7999841f7382348

# Social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@ScriptOps"

# Navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

safe: false
include: [".htaccess"]
exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

encoding: utf-8
keep_files: [".git", ".svn"]
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false